apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-postgresql:5432/backenddb
  SPRING_JPA_HIBERNATE_DDL_AUTO: update
  SERVER_PORT: "9090"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: health,metrics