@Library('devops-lib') _

pipeline {
    agent any
    
    environment {
        DOCKER_REGISTRY = 'alibaih123'
        APP_NAME = 'backend'
        NAMESPACE = 'dev'
        HELM_CHART = './helm/backend'
    }
    
    stages {
        stage('Checkout') {
            steps {
                checkout scm
                echo "Code checked out"
            }
        }
        
        stage('Build App') {
            steps {
                buildApp()
            }
        }
        
        stage('Run Tests') {
            steps {
                runTests()
            }
        }
        
        stage('Build Docker Image') {
            steps {
                buildDockerImage("${DOCKER_REGISTRY}/${APP_NAME}", "${BUILD_NUMBER}")
            }
        }
        
        stage('Push Docker Image') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'alibaih123/******',
                                                      usernameVariable: 'DOCKER_USER',
                                                      passwordVariable: 'DOCKER_PASS')]) {
                        sh """
                            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
                            docker push ${DOCKER_REGISTRY}/${APP_NAME}:${BUILD_NUMBER}
                            docker push ${DOCKER_REGISTRY}/${APP_NAME}:latest
                        """
                    }
                    echo "Image pushed to Docker Hub"
                }
            }
        }
        
        stage('Deploy with Helm') {
            steps {
                script {
                    withKubeConfig([credentialsId: 'kubeconfig-data']) {
                        deployHelmChart(HELM_CHART, APP_NAME, NAMESPACE, "${DOCKER_REGISTRY}/${APP_NAME}", "${BUILD_NUMBER}")
                    }
                }
            }
        }
        
        stage('Health Check') {
            steps {
                script {
                    withKubeConfig([credentialsId: 'kubeconfig-data']) {
                        sh """
                            kubectl wait --for=condition=ready pod -l app=${APP_NAME} \
                                --namespace ${NAMESPACE} --timeout=120s
                            echo "Application is healthy"
                        """
                    }
                }
            }
        }
    }
    
    post {
        success {
            echo "Pipeline SUCCESS! App deployed successfully!"
        }
        failure {
            echo "Pipeline FAILED! Check logs above."
        }
    }
}